name = "leitner-telegram-bot"
main = "src/index.ts"
compatibility_date = "2024-09-02"

# Enable advanced features
node_compat = true
minify = true

# Observability settings
[observability]
enabled = true

# Logpush configuration for detailed logging
[logpush]
enabled = true

# Tail worker logs configuration
[tail]
enabled = true

# Analytics and metrics
[analytics_engine_datasets]
[[analytics_engine_datasets]]
binding = "AE"

# Deploy configuration
[deploy]
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables - set these in your Cloudflare dashboard
# TELEGRAM_BOT_TOKEN = "your_telegram_bot_token"
# GEMINI_API_KEY = "your_gemini_api_key"
# WEBHOOK_SECRET = "your_webhook_secret"

[[kv_namespaces]]
binding = "LEITNER_DB"
preview_id = "8bcbcc5cfc054f27ad9e384b10adfa56"
id = "60580ee076484bd284f092cb5c6c1f79"

[triggers]
crons = ["0 8,14,20 * * *"]  # Daily reminders at 8 AM, 2 PM, and 8 PM

# Staging environment
[env.staging]
name = "leitner-telegram-bot-staging"
node_compat = true
minify = false  # Keep unminified for easier debugging in staging

[env.staging.observability]
enabled = true

[[env.staging.kv_namespaces]]
binding = "LEITNER_DB"
id = "60580ee076484bd284f092cb5c6c1f79"

[env.staging.triggers]
crons = ["0 9,15,21 * * *"]  # Staging reminders at different times
