name = "leitner-telegram-bot"
main = "src/index.ts"
compatibility_date = "2024-09-02"

[vars]
# Environment variables - set these in your Cloudflare dashboard
# TELEGRAM_BOT_TOKEN = "your_telegram_bot_token"
# GEMINI_API_KEY = "your_gemini_api_key"
# WEBHOOK_SECRET = "your_webhook_secret"

[[kv_namespaces]]
binding = "LEITNER_DB"
preview_id = "63f744fcdfea42faaa40435604feeecb"
id = "63f744fcdfea42faaa40435604feeecb"

[triggers]
crons = ["0 8,14,20 * * *"]  # Daily reminders at 8 AM, 2 PM, and 8 PM

# Staging environment
[env.staging]
name = "leitner-telegram-bot-staging"
[[env.staging.kv_namespaces]]
binding = "LEITNER_DB"
id = "63f744fcdfea42faaa40435604feeecb"

[env.staging.triggers]
crons = ["0 9,15,21 * * *"]  # Staging reminders at different times
