name = "leitner-telegram-bot"
main = "src/index.ts"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

# Enable advanced features
minify = true

# Analytics and metrics
[[analytics_engine_datasets]]
binding = "AE"

[vars]
# Environment variables - these will be set from GitHub secrets in CI/CD
TELEGRAM_BOT_TOKEN = "dummy_token_for_local_testing"
GEMINI_API_KEY = "dummy_gemini_key_for_local_testing"
WEBHOOK_SECRET = "dummy_webhook_secret_for_local_testing"

[[kv_namespaces]]
binding = "LEITNER_DB"
preview_id = "8bcbcc5cfc054f27ad9e384b10adfa56"
id = "60580ee076484bd284f092cb5c6c1f79"

[triggers]
crons = ["0 8,14,20 * * *"]  # Daily reminders at 8 AM, 2 PM, and 8 PM

# Staging environment
[env.staging]
name = "leitner-telegram-bot-staging"
compatibility_flags = ["nodejs_compat"]
minify = false  # Keep unminified for easier debugging in staging

[[env.staging.kv_namespaces]]
binding = "LEITNER_DB"
id = "60580ee076484bd284f092cb5c6c1f79"

[env.staging.triggers]
crons = ["0 9,15,21 * * *"]  # Staging reminders at different times
