name = "leitner-telegram-bot"
main = "src/index.ts"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

# Enable advanced features
minify = true

# Analytics and metrics
[[analytics_engine_datasets]]
binding = "AE"

[vars]
# Environment variables - these are set via GitHub secrets in CI/CD
# For local development, set these in your Cloudflare dashboard or use .dev.vars file
# TELEGRAM_BOT_TOKEN = "your_real_token"
# GEMINI_API_KEY = "your_real_key"  
# WEBHOOK_SECRET = "your_real_secret"

[[kv_namespaces]]
binding = "LEITNER_DB"
preview_id = "8bcbcc5cfc054f27ad9e384b10adfa56"
id = "60580ee076484bd284f092cb5c6c1f79"

[triggers]
crons = ["0 8,14,20 * * *"]  # Daily reminders at 8 AM, 2 PM, and 8 PM

# Staging environment
[env.staging]
name = "leitner-telegram-bot-staging"
compatibility_flags = ["nodejs_compat"]
minify = false  # Keep unminified for easier debugging in staging

[[env.staging.kv_namespaces]]
binding = "LEITNER_DB"
id = "60580ee076484bd284f092cb5c6c1f79"

[env.staging.triggers]
crons = ["0 9,15,21 * * *"]  # Staging reminders at different times
