name = "leitner-telegram-bot"
main = "src/index.ts"
compatibility_date = "2024-09-02"
compatibility_flags = ["nodejs_compat"]

# Enable advanced features
minify = true

# Analytics and metrics
[[analytics_engine_datasets]]
binding = "AE"

[vars]
# Environment variables will be set as secrets via wrangler secret put
# No dummy values needed - secrets will override

[[kv_namespaces]]
binding = "LEITNER_DB"
preview_id = "8bcbcc5cfc054f27ad9e384b10adfa56"
id = "60580ee076484bd284f092cb5c6c1f79"

[triggers]
crons = ["0 8,14,20 * * *"]  # Daily reminders at 8 AM, 2 PM, and 8 PM
