name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy

      - name: Setup Telegram Webhook
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          WORKER_URL: https://leitner-telegram-bot.t-ak-sa.workers.dev
          GITHUB_ACTIONS: true
        run: |
          echo "🚀 Setting up Telegram webhook after deployment..."
          sleep 5  # Wait for deployment to propagate
          node scripts/setup-webhook.js
        
      - name: Deployment Summary
        if: always()
        run: |
          echo "🎉 Deployment completed!"
          echo "📱 Bot URL: https://leitner-telegram-bot.t-ak-sa.workers.dev"
          echo "🔧 Admin Panel: https://leitner-telegram-bot.t-ak-sa.workers.dev/admin"
          echo "📊 Health Check: https://leitner-telegram-bot.t-ak-sa.workers.dev/health"
