name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allow manual deployment

env:
  NODE_VERSION: '18'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    name: Test and Build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Build TypeScript
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production
    needs: test-and-build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}

      - name: Wait for deployment to propagate
        run: sleep 10

      - name: Setup Telegram Webhook
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          WORKER_URL: ${{ secrets.WORKER_URL || 'https://leitner-telegram-bot.t-ak-sa.workers.dev' }}
          GITHUB_ACTIONS: true
        run: |
          echo "🚀 Setting up Telegram webhook after deployment..."
          node scripts/setup-webhook.js
        
      - name: Deployment Summary
        if: always()
        run: |
          echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Worker URL**: ${{ secrets.WORKER_URL || 'https://leitner-telegram-bot.t-ak-sa.workers.dev' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo ""
          echo "🎉 Deployment completed!"
          echo "📱 Bot URL: https://leitner-telegram-bot.t-ak-sa.workers.dev"
          echo "🔧 Admin Panel: https://leitner-telegram-bot.t-ak-sa.workers.dev/admin"
          echo "📊 Health Check: https://leitner-telegram-bot.t-ak-sa.workers.dev/health"
